name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.141.0'
          extended: true

      - name: Build with Hugo
        run: hugo --minify

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: "d9e20e772936d6f7f9c70c687b13c805159c0ae5ceb17e57164fd568cfe70d0f01-98a5103b-281a-4376-9066-542b324e918f01020290b1e2b510"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          
          action: "upload"
          app_location: "/"
          output_location: "public"
